
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analiseSintatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 7;
  public static final int BOOL = 87;
  public static final int MAIOR_QUE = 31;
  public static final int TIPOINT = 81;
  public static final int MENOR_IGUAL = 36;
  public static final int MENOR_QUE = 32;
  public static final int ARROW = 27;
  public static final int DOISPONTOS = 48;
  public static final int TYPE = 75;
  public static final int GO = 63;
  public static final int CHAVEESQ = 42;
  public static final int CONST = 55;
  public static final int INTEIRO = 89;
  public static final int SUBTRACAO = 3;
  public static final int VIRGULA = 46;
  public static final int FUNC = 62;
  public static final int DEFER = 58;
  public static final int unicode_char = 92;
  public static final int TIPOFLOAT32 = 82;
  public static final int ATRIBUICAO = 33;
  public static final int DIFERENTE = 35;
  public static final int COLCHESQ = 44;
  public static final int DEFINE = 38;
  public static final int ATRIBUICAO_AND = 19;
  public static final int PARENDIR = 41;
  public static final int ATRIBUICAO_XOR = 21;
  public static final int STRUCT = 73;
  public static final int NOT = 34;
  public static final int DEC = 29;
  public static final int VAR = 76;
  public static final int FLOAT = 90;
  public static final int GOTO = 64;
  public static final int PACKAGE = 69;
  public static final int DIVISAO = 5;
  public static final int LOR = 26;
  public static final int unicode_value = 93;
  public static final int SHIFT_LEFT = 11;
  public static final int UNTYPEDNIL = 78;
  public static final int SELECT = 72;
  public static final int ASPAS = 51;
  public static final int FALLTHROUGH = 60;
  public static final int IGUAL = 30;
  public static final int PONTO = 47;
  public static final int INTERFACE = 67;
  public static final int ATRIBUICAO_SUB = 15;
  public static final int MAIOR_IGUAL = 37;
  public static final int CHAN = 54;
  public static final int SWITCH = 74;
  public static final int FOR = 61;
  public static final int UNTYPEDSTRING = 79;
  public static final int PARENESQ = 40;
  public static final int RETURN = 71;
  public static final int ATRIBUICAO_OR = 20;
  public static final int ELSE = 59;
  public static final int AND_NOT = 13;
  public static final int BREAK = 52;
  public static final int INICIOCOMENT = 84;
  public static final int MAP = 68;
  public static final int EOF = 0;
  public static final int SHIFT_RIGHT = 12;
  public static final int ATRIBUICAO_MULT = 16;
  public static final int DEFAULT = 57;
  public static final int APOSTROFO = 50;
  public static final int TIPOFLOAT64 = 83;
  public static final int INC = 28;
  public static final int RESTO = 6;
  public static final int IMPORT = 66;
  public static final int CHAVEDIR = 43;
  public static final int OR = 9;
  public static final int error = 1;
  public static final int CONTINUE = 56;
  public static final int IF = 65;
  public static final int ID = 91;
  public static final int TIPOBOOL = 77;
  public static final int ATRIBUICAO_DIV = 17;
  public static final int TIPOSTRING = 80;
  public static final int COLCHDIR = 45;
  public static final int byte_value = 95;
  public static final int SOMA = 2;
  public static final int FINALCOMENT = 85;
  public static final int BRANCO = 86;
  public static final int CASE = 53;
  public static final int newline = 94;
  public static final int ATRICUICAO_AND_NOT = 24;
  public static final int ATRIBUICAO_RESTO = 18;
  public static final int RANGE = 70;
  public static final int ATRIBUICAO_SR = 23;
  public static final int ATRIBUICAO_SOMA = 14;
  public static final int LAND = 25;
  public static final int PONTOVIRGULA = 49;
  public static final int AND = 8;
  public static final int COMPLEX = 88;
  public static final int ELLIPSIS = 39;
  public static final int ATRIBUICAO_SL = 22;
  public static final int MULTIPLICACAO = 4;
  public static final int XOR = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SOMA",
  "SUBTRACAO",
  "MULTIPLICACAO",
  "DIVISAO",
  "RESTO",
  "IDENTIFICADOR",
  "AND",
  "OR",
  "XOR",
  "SHIFT_LEFT",
  "SHIFT_RIGHT",
  "AND_NOT",
  "ATRIBUICAO_SOMA",
  "ATRIBUICAO_SUB",
  "ATRIBUICAO_MULT",
  "ATRIBUICAO_DIV",
  "ATRIBUICAO_RESTO",
  "ATRIBUICAO_AND",
  "ATRIBUICAO_OR",
  "ATRIBUICAO_XOR",
  "ATRIBUICAO_SL",
  "ATRIBUICAO_SR",
  "ATRICUICAO_AND_NOT",
  "LAND",
  "LOR",
  "ARROW",
  "INC",
  "DEC",
  "IGUAL",
  "MAIOR_QUE",
  "MENOR_QUE",
  "ATRIBUICAO",
  "NOT",
  "DIFERENTE",
  "MENOR_IGUAL",
  "MAIOR_IGUAL",
  "DEFINE",
  "ELLIPSIS",
  "PARENESQ",
  "PARENDIR",
  "CHAVEESQ",
  "CHAVEDIR",
  "COLCHESQ",
  "COLCHDIR",
  "VIRGULA",
  "PONTO",
  "DOISPONTOS",
  "PONTOVIRGULA",
  "APOSTROFO",
  "ASPAS",
  "BREAK",
  "CASE",
  "CHAN",
  "CONST",
  "CONTINUE",
  "DEFAULT",
  "DEFER",
  "ELSE",
  "FALLTHROUGH",
  "FOR",
  "FUNC",
  "GO",
  "GOTO",
  "IF",
  "IMPORT",
  "INTERFACE",
  "MAP",
  "PACKAGE",
  "RANGE",
  "RETURN",
  "SELECT",
  "STRUCT",
  "SWITCH",
  "TYPE",
  "VAR",
  "TIPOBOOL",
  "UNTYPEDNIL",
  "UNTYPEDSTRING",
  "TIPOSTRING",
  "TIPOINT",
  "TIPOFLOAT32",
  "TIPOFLOAT64",
  "INICIOCOMENT",
  "FINALCOMENT",
  "BRANCO",
  "BOOL",
  "COMPLEX",
  "INTEIRO",
  "FLOAT",
  "ID",
  "unicode_char",
  "unicode_value",
  "newline",
  "byte_value"
  };
}

